# Generated by Django 5.2.2 on 2025-06-11 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancelog',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
