# Generated by Django 5.1.5 on 2025-01-17 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='code',
            new_name='employeeCode',
        ),
    ]
