# Generated by Django 5.2.2 on 2025-06-11 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0002_rename_employee_id_attendancelog_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoLibrary',
        ),
    ]
