# Generated by Django 5.1.5 on 2025-01-27 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0003_alter_employee_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
    ]
