# Generated by Django 5.2.3 on 2025-06-23 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0003_delete_photolibrary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_type', models.CharField(choices=[('IN', 'Punch In'), ('OUT', 'Punch Out')], max_length=3)),
                ('date', models.DateField()),
                ('corrected_time', models.TimeField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('attendance_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendanceApp.attendancelog')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceApp.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_corrections', to='attendanceApp.employee')),
            ],
        ),
    ]
