# Generated by Django 5.1.5 on 2025-02-23 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0005_remove_attendancelog_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancelog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attendancelog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='attendancelog',
            name='time_in',
        ),
        migrations.RemoveField(
            model_name='attendancelog',
            name='time_out',
        ),
    ]
