# Generated by Django 5.2.3 on 2025-06-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0005_alter_correctionrequest_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('present', 'Present'), ('absent', 'Absent'), ('weekend', 'Weekend'), ('public_holiday', 'Public Holiday')], default='absent', max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendancelog',
            unique_together={('employee', 'att_date_time')},
        ),
    ]
