# Generated by Django 5.1.5 on 2025-01-28 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0005_alter_project_employees_alter_project_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='employees',
        ),
    ]
