# Generated by Django 5.2.4 on 2025-07-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0006_alter_attendancelog_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancelog',
            unique_together=set(),
        ),
    ]
