# Generated by Django 5.1.5 on 2025-02-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0006_remove_attendancelog_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='standardPhotos/'),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='selfies/'),
        ),
        migrations.AlterField(
            model_name='photolibrary',
            name='image',
            field=models.ImageField(upload_to='standardPhotos/'),
        ),
    ]
