# Generated by Django 5.1.5 on 2025-01-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0007_project_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='location',
            field=models.JSONField(),
        ),
    ]
