# Generated by Django 5.1.5 on 2025-02-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0007_employee_photo_alter_attendancelog_selfie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo_encoding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
