# Generated by Django 5.1.5 on 2025-01-28 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0008_alter_attendancelog_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
    ]
