# Generated by Django 5.1.5 on 2025-01-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0009_remove_project_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
