# Generated by Django 5.1.7 on 2025-03-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0010_alter_employee_photo_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
