# Generated by Django 5.1.7 on 2025-03-16 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0011_attendancelog_date_attendancelog_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancelog',
            old_name='time',
            new_name='time_in',
        ),
    ]
