# Generated by Django 5.1.5 on 2025-01-29 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0012_alter_project_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancelog',
            name='location',
        ),
    ]
