# Generated by Django 5.1.7 on 2025-03-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0012_rename_time_attendancelog_time_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='location',
            field=models.CharField(blank=True, null=True),
        ),
    ]
