# Generated by Django 5.1.5 on 2025-01-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0013_remove_attendancelog_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='location',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
