# Generated by Django 5.1.7 on 2025-03-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0013_alter_attendancelog_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='status',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent'), ('weekend', 'Weekend'), ('public_holiday', 'Public Holiday')], default='present', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
