# Generated by Django 5.1.5 on 2025-01-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0014_remove_project_location_attendancelog_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lcation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
