# Generated by Django 5.1.7 on 2025-03-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0014_attendancelog_status_attendancelog_time_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='status',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent'), ('weekend', 'Weekend'), ('public_holiday', 'Public Holiday')], default='Present', max_length=20, null=True),
        ),
    ]
