# Generated by Django 5.1.5 on 2025-01-29 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0015_project_lcation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='lcation',
            new_name='location',
        ),
    ]
