# Generated by Django 5.2 on 2025-06-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0016_workshift_attendancelog_shift_employee_work_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='total_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('present', 'Present'), ('absent', 'Absent'), ('weekend', 'Weekend'), ('public_holiday', 'Public Holiday')], default='Present', max_length=20, null=True),
        ),
    ]
