# Generated by Django 5.1.5 on 2025-01-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0016_rename_lcation_project_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='range',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
