# Generated by Django 5.1.5 on 2025-02-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0018_rename_range_project_attendancerange'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(blank=True, null=True, to='attendanceApp.employee'),
        ),
    ]
