# Generated by Django 5.1.5 on 2025-02-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0020_alter_project_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='employees',
        ),
    ]
