# Generated by Django 5.1.5 on 2025-02-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0021_remove_project_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='projects',
            field=models.ManyToManyField(blank=True, to='attendanceApp.project'),
        ),
    ]
