# Generated by Django 5.1.5 on 2025-02-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0022_attendancelog_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancelog',
            name='projects',
        ),
        migrations.AddField(
            model_name='employee',
            name='projects',
            field=models.ManyToManyField(blank=True, to='attendanceApp.project'),
        ),
    ]
