# Generated by Django 5.1.5 on 2025-02-11 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0025_alter_employee_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='user',
            new_name='user_id',
        ),
    ]
