# Generated by Django 5.1.5 on 2025-02-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0031_alter_employee_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancelog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attendancelog',
            name='time_in',
        ),
        migrations.RemoveField(
            model_name='attendancelog',
            name='time_out',
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='att_date_time',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
