# Generated by Django 5.1.5 on 2025-02-20 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0032_remove_attendancelog_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='att_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendanceApp.employee'),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
