# Generated by Django 5.1.5 on 2025-02-20 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0033_alter_attendancelog_att_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancelog',
            name='att_date_time',
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='date',
            field=models.DateField(default=-2025),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='time_in',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='time_out',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendanceApp.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='location',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='photo',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
