# Generated by Django 5.1.5 on 2025-02-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0033_alter_attendancelog_att_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancelog',
            name='att_date_time',
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
